# Generated by Django 6.0.6 on 2026-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poyezd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tezlik', models.IntegerField()),
                ('joylar_soni', models.IntegerField()),
                ('yoqilgi_turi', models.CharField(max_length=50)),
            ],
        ),
    ]
