# Generated by Django 6.0.6 on 2026-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartSoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soni', models.IntegerField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
