# Generated by Django 6.0.6 on 2026-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narxi', models.IntegerField()),
                ('haqida', models.TextField(blank=True, null=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('sotilgan_vaqt', models.TimeField(blank=True, null=True)),
                ('mavjudmi', models.BooleanField(default=True)),
                ('soni', models.FloatField()),
            ],
        ),
    ]
